namespace HE.Remediation.Core.Enums;

public enum ECladdingSystemType
{
    CementFibre = 1,
    CeramicTile = 2,
    ClayTile = 3,
    ConcreteInSituPrecastFaced = 4,
    CurtainWallGlazedOrSolidPanel = 5,
    EticsRender = 6,
    FibreGlass = 7,
    Glass = 8,
    HighPressureLaminateHpl = 9,
    MasonryWithOrWithoutRender = 10,
    MetalCompositePanelAcmCategory1 = 11,
    MetalCompositePanelAcmCategory2 = 12,
    MetalCompositePanelAcmCategory3 = 13,
    MetalCompositePanelMcmCategory1 = 14,
    MetalCompositePanelMcmCategory2 = 15,
    MetalCompositePanelMcmCategory3 = 16,
    MetalCompositePanelUnknown = 17,
    MetalPanelAluminium = 18,
    MetalPanelCopper = 19,
    MetalPanelOther = 20,
    MetalPanelSteel = 21,
    MetalPanelUnknown = 22,
    MetalPanelZinc = 23,
    NaturalStone = 24,
    Plastics = 25,
    ReconstitutedStone = 26,
    SandwichPanel = 27,
    StoneTile = 28,
    Timber = 29,
    Other = 30
}