CREATE TABLE [dbo].[ApplicationResponsibleEntity] (
    [Id] UNIQUEIDENTIFIER NOT NULL,
    [RepresentationTypeId] INT NULL,
    [BuildingRelationshipId] INT NULL,
    [OrganisationId] INT NULL,
    [OrganisationSubTypeId] INT NULL,
    [OrganisationSubTypeDescription] NVARCHAR(1000) NULL,
    [UkRegistered] BIT NULL,
    [CompanyName] NVARCHAR (150) NULL,
    [CompanyRegistrationNumber] NVARCHAR (150) NULL,
    [AddressId] UNIQUEIDENTIFIER NULL,
    [FirstName] NVARCHAR (150) NULL,
    [LastName] NVARCHAR (150) NULL,
    [EmailAddress] NVARCHAR (150) NULL,
    [ContactNumber] NVARCHAR (150) NULL,
    [TaskStatusId] INT CONSTRAINT [DF_ApplicationResponsibleEntity_Status] DEFAULT ((1)) NOT NULL,
    [RepresentationEntityDetailsId] UNIQUEIDENTIFIER NULL,
    [FreeholderId] UNIQUEIDENTIFIER NULL,
    [HasOwners] BIT NULL,
    [SharedOwnerCount] INT NULL,
    [IsClaimingGrant] BIT NULL,
    [IsConfirmedNotViable] BIT NULL,
    [IsRepresentativeUkBased] BIT NULL,
    CONSTRAINT [PK_ApplicationResponseibleEntity] PRIMARY KEY CLUSTERED ([Id]),
    CONSTRAINT [FK_dbo.ApplicationResponsibleEntity_dbo.TaskStatus_TaskStatusID] FOREIGN KEY ([TaskStatusId]) REFERENCES [dbo].[TaskStatus] ([Id]),
    CONSTRAINT [FK_ApplicationResponsibleEntity_RepresentationTypeId] FOREIGN KEY ([RepresentationTypeId]) REFERENCES [dbo].[ApplicationRepresentationType] ([Id]),
    CONSTRAINT [FK_ApplicationResponsibleEntity_BuildingRelationshipId] FOREIGN KEY ([BuildingRelationshipId]) REFERENCES [dbo].[ApplicationBuildingRelationship] ([Id]),
    CONSTRAINT [FK_ApplicationResponsibleEntity_OrganisationId] FOREIGN KEY ([OrganisationId]) REFERENCES [dbo].[ApplicationResponsibleEntityOrganisation] ([Id]),
    CONSTRAINT [FK_ApplicationResponsibleEntity_OrganisationSubTypeId] FOREIGN KEY ([OrganisationSubTypeId]) REFERENCES [dbo].[ApplicationResponsibleEntityOrganisationSubType] ([Id]),
    CONSTRAINT [FK_ApplicationResponsibleEntity_AddressId] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Address] ([Id]),
    CONSTRAINT [FK_ApplicationResponsibleEntity_FreeholderId] FOREIGN KEY ([FreeholderId]) REFERENCES [dbo].[ApplicationResponsibleEntityFreeholder] ([Id]),
    CONSTRAINT [FK_ApplicationResponsibleEntity_ApplicationRepresentationEntityDetails] FOREIGN KEY ([RepresentationEntityDetailsId]) REFERENCES [dbo].[ApplicationRepresentationEntityDetails] ([Id])
);